### ISSUE TITLE
Migrating skill definitions and feedback form responses

### ISSUE THREAD

**Issue by rosenhouse** [pivotal-cf/areas-of-contribution#21]
## Motivation
In order to reduce the cost of change to this repo (#11), a skill definition needs to be changeable.  For some kinds of change, like a typo fix, the feedback form responses collected against the original definition should be carried forward to the new definitions.  In other cases, like deleting a skill definition entirely, or substantially changing the meaning of a skill definition, the responses might be preserved somehow, but shouldn't be recorded as applying to a new skill definition.

The author of a change to a skill definition ought to be able to define how the response data to the original definition should be handled.  This would be specifying a "migration."

Below we propose how a contributor to this repo might specify a migration, using a simple YAML syntax.

## To `update` or not to `update`
There are 3 `type`s of change:
- `create`
- `delete`
- `update`

Feedback responses to `delete`d skills are archived, but not migrated anywhere.

Conversely, an `update` results in the feedback responses being migrated to the new skill definition.

## Schema examples
We'll illustrate the proposed schema with a few examples

1. Typo fix.  Preserve existing responses.
   ```yaml
   changes:
   - type: update
     # typo fix delviery --> delivery
     old:
       area: Technical Execution
       level: P4
       definition: "Can navigate their way through legacy systems and improve throughput of the team (eg: notices complex code paths are slowing down feature delviery, facilitates conversations with the team on how to simplify them, gets buy-in from PM+leadership to prioritize this work, drives it to completion with the team.)"
     new:
       area: Technical Execution
       level: P4
       definition: "Can navigate their way through legacy systems and improve throughput of the team (eg: notices complex code paths are slowing down feature delivery, facilitates conversations with the team on how to simplify them, gets buy-in from PM+leadership to prioritize this work, drives it to completion with the team.)"
   ```

0. Change the P-level associated with a skill definition.  Preserve existing responses.
   ```yaml
   changes:
   - type: update
     old:
       area: Technical Execution
       level: P2
       definition: "Discusses the balance of short term execution with long term health"
     new:
       area: Technical Execution
       level: P3
       definition: "Discusses the balance of short term execution with long term health"
   ```

0. Change the meaning of a skill definition and its P-level.  Do not apply old responses to the new skill.
   ```yaml
   changes:
   - type: delete
     old:
       area: Technical Execution
       level: P2
       definition: "Discusses the balance of short term execution with long term health"
   - type: create
     new:
       area: Technical Execution
       level: P3
       definition: "Calibrates pace of execution to balance short-term delivery with long-term health"
   ```

0. Split up a single skill definition into multiple definitions.  Do not apply old responses to new skills.
   ```yaml
   changes:
   - type: delete
     old:
       area: Technical Decision-Making
       level: P2
       definition: "Surfaces and discusses various factors (outlined in P3+) when approaching a technical decision, with support from other pivots to make the final decision."
   - type: create
     new:
       area: Technical Decision-Making
       level: P2
       definition: "Surfaces and discusses maintainability when approaching a technical decision, with support from other pivots to make the final decision."
   - type: create
     new:
       area: Technical Decision-Making
       level: P2
       definition: "Surfaces and discusses support when approaching a technical decision, with support from other pivots to make the final decision."
   - type: create
     new:
       area: Technical Decision-Making
       level: P2
       definition: "Surfaces and discusses performance when approaching a technical decision, with support from other pivots to make the final decision."
   ...
   ```

## Data migration
- `type: update` will modify an item.  It will always preserve existing response data
- changes that affect the meaning of an item should not be expressed as an `update` but instead as a `delete` followed by an `insert`.  This will cause existing response data to not be migrated to the new item.

## Feedback?
Please leave thoughts and questions below!

**Comment by rosenhouse** [comment]
Updated this in response to feedback.  Schema is now somewhat simpler, and more directly maps to the APIs on Google Forms that we'll need to drive in order to implement this.

**Comment by aramprice** [comment]
Would each `changes:` set live it its own file?

It seems like the YAML below could mean either:
- "Question-X => Question-Y, Question-Z"
- "Question-X => Question-Y, "add Question-Z"

```yaml
- type: delete
  old:
    area: Technical Decision-Making
    level: P2
    definition: "Question-X"
- type: create
  new:
    area: Technical Decision-Making
    level: P2
    definition: "Question-Y"
- type: create
  new:
    area: Technical Decision-Making
    level: P2
    definition: "Question-Z"
```
