### ISSUE TITLE
Skill annotation: observable_by

### ISSUE THREAD

**Issue by rosenhouse** [pivotal-cf/areas-of-contribution#26]
### Problem
When collecting feedback from an engineer's PM or LL, the set of relevant questions are often spread across several skill areas, and may not be immediately discoverable.

Alternately, there are some skill definitions that are rarely observable by anyone other than a Pivot's manager. 

### Possible solution
One benefit of the new yaml format (#23) is that individual skills may be annotated with additional metadata. 

For example, right now we've got
```yaml
  - id: sb975bf39
    description: >-
      Is aligned with the priorities of the organization, and approaches their team allocation as a
      collaborative effort with leadership.
    area: alignment
    level: p4
```

but we could easily add new, optional `key: value` pairs that encode other useful information.  

For example:

```diff
  - id: sb975bf39
    description: >-
      Is aligned with the priorities of the organization, and approaches their team allocation as a
      collaborative effort with leadership.
    area: alignment
    level: p4
+   observable_by: [manager, LL]
```

Another example:
```diff
  - id: s5c7c3275
    description: "Pairs with PM+Design on technical solutioning (eg: in pre-IPM, preparing for inception, etc.)"
    area: project-leadership
    level: p2
+   observable_by: [PM, anchor]
```

We could easily provide "filtered" views of the skills that would help with "what questions should I ask their LL?"

Thanks to @dsabeti for the idea!
